[package]
name = "my_first_rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.7.2"

[build-dependencies]
slint-build = "1.7.2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
